### ISSUE TITLE
Perfect-libxml2 version on swift 4.1 

### ISSUE THREAD

**Issue by dejavuwing** [PerfectlySoft/Perfect-XML#5]
Hi,
I'm using xcode 9.3 and swift 4.1.
My API project has adopted a Postgres-StORM. But I found an error in xcode issue with Perfect-libxml2.
I checked that Perfect-libxml2 has updated to 3.0.0. I'm looking forward to updating for Perfect-libxml2 in Perfect-XML.
Thank you.

**Comment by duannl** [comment]
Please update. Thanks :)

**Comment by iamjono** [comment]
What's the error please?

**Comment by duannl** [comment]
This is the error:
<img width="1116" alt="screen shot 2018-04-03 at 9 24 10 pm" src="https://user-images.githubusercontent.com/2805068/38255314-b8fe0592-3785-11e8-8fbc-6ba70a105355.png">
And the Package.swift of Perfect-XML is:
<img width="762" alt="screen shot 2018-04-03 at 9 27 28 pm" src="https://user-images.githubusercontent.com/2805068/38255378-de4922c8-3785-11e8-8cf1-c748ea4c9385.png">

**Comment by iamjono** [comment]
If you got this error because you are using Postgre-StORM, please run `swift package update` to get the latest version of Postgres-StORM. This temporarily removes the inclusion of `libxml2` until this is updated to avoid the conflict with Swift 4.1's inclusion of it.

**Comment by RockfordWei** [comment]
SPM works well but it only fails in Xcode so it is a namespace issue. Suggest to rename "libxml" to "PerfectLibXML" or something.

**Comment by duannl** [comment]
@iamjono awesome. Just one more thing I have to do is run `swift package generate-xcodeproj`. Thank you very much

**Comment by kjessup** [comment]
This should be completely fixed. Can I get a confirmation?

**Comment by kjessup** [comment]
I don't see any issues on my end, so I'll assume it's fixed until I hear otherwise.
